apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agent-workflow
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: mongodb-headless.default.svc.cluster.local:27017
  - name: databaseName
    value: sredb
  - name: params
    value: "?replicaSet=rs0"
  - name: actorStateStore
    value: "true"
